version: '3.1'
services:
  frontend:
    build:
      context: ./frontendVitkon17
      dockerfile: Dockerfile-frontend
    ports:
      - 443:443
    volumes:
      - ./frontendVitkon17:/app
      - /app/node_modules
      
  tgfrontend:
    build:
      context: ./tg_app
      dockerfile: Dockerfile-frontend
    ports:
      - 8060:8060
    volumes:
      - ./tg_app:/app
      - /app/node_modules  

  # desktop:
  #   build:
  #     context: ./frontendVitkon17_exe
  #     dockerfile: Dockerfile-frontend-desktop
  #   ports:
  #     - 85:85
  #   volumes:
  #     - ./frontendVitkon17_exe:/app
  #     - /app/node_modules

  backend:
    build:
      context: ./serverVITKON
      dockerfile: Dockerfile-backend
    ports:
      - "8000:8000"
    

  # db:
  #   image: mariadb:10.6
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: nikit

  # phpmyadmin:
  #   image: phpmyadmin
  #   restart: always
  #   ports:
  #     - 8030:80
  #   environment:
  #     - PMA_ARBITRARY=1
      
  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080


