services:
  frontend:
    build:
      context: ./frontendVitkon17
      dockerfile: Dockerfile-frontend
    ports:
      - 80:80
    volumes:
      - ./frontendVitkon17:/app
      - /app/node_modules

